In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from matplotlib import pyplot as plt

In [3]:
dataset = pd.read_csv("C:\\Users\\NISHANT\\3D Objects\\CSV_Files\\IRIS.csv")

In [4]:
dataset

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
x = dataset.iloc[:,[0,1,2,3]].values

In [6]:
y = dataset.iloc[:,4].values

In [7]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state=1)

In [11]:
x_train

array([[6.5, 2.8, 4.6, 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3. , 5.5, 2.1],
       [5.1, 3.5, 1.4, 0.3],
       [6. , 2.2, 5. , 1.5],
       [6.3, 2.9, 5.6, 1.8],
       [6.6, 2.9, 4.6, 1.3],
       [7.7, 2.6, 6.9, 2.3],
       [5.7, 3.8, 1.7, 0.3],
       [5. , 3.6, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.1, 3.4, 1.5, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [6.9, 3.1, 5.4, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.4, 2.8, 5.6, 2.2],
       [6.2, 2.8, 4.8, 1.8],
       [6. , 3.4, 4.5, 1.6],
       [7.7, 2.8, 6.7, 2. ],
       [5.7, 3. , 4.2, 1.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3. , 1.4, 0.1],
       [4.7, 3.2, 1.3, 0.2],
       [6.5, 3. , 5.8, 2.2],
       [4.6, 3.4, 1.4, 0.3],
       [6.1, 3. , 4.9, 1.8],
       [6.5, 3.2, 5.1, 2. ],
       [6.7, 3.1, 4.4, 1.4],
       [5.7, 2.8, 4.5, 1.3],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 3

In [12]:
y_train

array(['Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
ss = StandardScaler()

In [15]:
x_train = ss.fit_transform(x_train)

In [16]:
x_test = ss.transform(x_test)

In [17]:
x_train

array([[ 8.03473255e-01, -5.32605965e-01,  4.54251771e-01,
         3.80020799e-01],
       [ 1.04344393e+00, -1.25712258e+00,  1.13184820e+00,
         7.69310398e-01],
       [ 1.16342927e+00, -4.95948874e-02,  9.62449091e-01,
         1.15860000e+00],
       [-8.76321497e-01,  1.15793281e+00, -1.35267203e+00,
        -1.17713760e+00],
       [ 2.03546558e-01, -1.98163920e+00,  6.80117246e-01,
         3.80020799e-01],
       [ 5.63502576e-01, -2.91100426e-01,  1.01891546e+00,
         7.69310398e-01],
       [ 9.23458594e-01, -2.91100426e-01,  4.54251771e-01,
         1.20494400e-01],
       [ 2.24329733e+00, -1.01561704e+00,  1.75297825e+00,
         1.41812640e+00],
       [-1.56409460e-01,  1.88244942e+00, -1.18327293e+00,
        -1.17713760e+00],
       [-9.96306836e-01,  1.39943835e+00, -1.35267203e+00,
        -1.30690080e+00],
       [-1.23627752e+00, -4.95948874e-02, -1.35267203e+00,
        -1.17713760e+00],
       [-7.56336157e-01, -7.74111504e-01,  5.89871889e-02,
      

In [18]:
x_test

array([[-0.03642412,  2.3654605 , -1.46560477, -1.3069008 ],
       [-0.8763215 , -1.25712258, -0.44921013, -0.139032  ],
       [ 0.92345859, -0.04959489,  0.34131903,  0.2502576 ],
       [-0.51636548,  2.12395496, -1.4091384 , -1.0473744 ],
       [ 2.48326801,  1.88244942,  1.47064641,  1.0288368 ],
       [ 0.56350258,  0.67492173,  0.51071814,  0.509784  ],
       [ 1.28341461,  0.19191065,  0.73658362,  1.4181264 ],
       [-0.8763215 ,  1.88244942, -1.07034019, -1.0473744 ],
       [-1.35626285,  0.43341619, -1.2397393 , -1.3069008 ],
       [ 1.28341461,  0.43341619,  1.07538183,  1.4181264 ],
       [-0.2763948 , -0.7741115 ,  0.2283863 ,  0.1204944 ],
       [-0.51636548,  2.12395496, -1.18327293, -1.0473744 ],
       [ 1.52338529, -0.04959489,  1.18831457,  1.1586    ],
       [ 0.68348792,  0.43341619,  0.3977854 ,  0.3800208 ],
       [ 0.20354656, -0.29110043,  0.3977854 ,  0.3800208 ],
       [-1.71621887,  0.43341619, -1.4091384 , -1.3069008 ],
       [-0.03642412, -1.

In [23]:
from sklearn.svm import SVC

In [29]:
classifier = SVC(kernel="linear",random_state = 1)

In [30]:
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=1)

In [31]:
classifier.predict([[ 1.28341461,  0.43341619,  1.07538183,  1.4181264 ]])

array(['Iris-virginica'], dtype=object)

In [32]:
y_test

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa'],
      dtype=object)

In [37]:
y_pred = classifier.predict(x_test)

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
print(confusion_matrix(y_test,y_pred))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [40]:
from sklearn.metrics import accuracy_score

In [41]:
print((accuracy_score(y_test,y_pred)*100),"%")

97.36842105263158 %
